### ISSUE TITLE
Bug: Color Roles

### ISSUE THREAD

**Issue by flloschy** [Cowoding-Jams/Jambo#28]
### Describe the bug

The bot only adds roles when selecting a color and doesn't remove the previous color

### Steps to reproduce

Select a few colors

### Expected behavior

Remove old color role

### Screenshots

![image](https://user-images.githubusercontent.com/69321390/193550092-c5accf3c-0232-4837-b5f9-89111e1071a3.png)

### Additional context

No more context :)

**Comment by StrangeGirlMurph** [comment]
Honestly I think I am totally fine with that :)
I have no problem with a person having all the color roles. And for the pronoun roles it's also necessary for people to be able to select multiple.

**Comment by flloschy** [comment]
Yea, but you *couldn't* remove color roles. But that changed now
